export default [
  { name: "Adaptability", id: "Adaptability" },
  { name: "Attention to detail", id: "attentionToDetail" },
  { name: "Critical Thinking", id: "criticalThinking" },
  { name: "Effective Communication", id: "communication" },
  { name: "Listening", id: "listening" },
  { name: "Ability to Manage Stress", id: "stressManagement" },
  { name: "Manual Dexterity", id: "manualDexterity" },
  { name: "Good Memory", id: "memory" },
  { name: "Multitasking", id: "multitasking" },
  { name: "Self-confidence", id: "selfConfidence" },
  { name: "Self-control", id: "selfControl" },
  { name: "Stamina", id: "stamina" },
  { name: "Team work", id: "teamwork" },
  { name: "Time Management", id: "timeManagement" },
];
